### ISSUE TITLE
link to WhatsApp from computer

### ISSUE THREAD

**Issue by dasaderi** [the-method/podcast#9]
The link to the WhatsApp chat you have on the README.md doesn't lead to anything in the computer. I don't know how to use WhatsApp from a computer, but there must a be a way.

**Comment by aprilcs** [comment]
There is a way! The invite link works on when you click from a device that has WhatsApp installed. If you have WhatsApp on your phone, clicking the link on your phone will bring you to the group. If you have WhatsApp and want to join the group from a computer, you can download WhatsApp and install it on your computer [here](https://www.whatsapp.com/download/).

**Comment by dasaderi** [comment]
Got it! Thank you.
